version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: echo ${master}

  test:
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: mvn -f ~/repo/spend/pom.xml test

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test
    